name: Build app
on: workflow_dispatch
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v2

      - name: Setup ndk
        uses: nttld/setup-ndk@v1
        with:
          ndk-version: r21d

      - name: Build the app
        run: |
          ./gradlew assembleDebug
        working-directory: ./app

      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: app-debug
          path: ./**/*.apk
